Update __init__.py
Fix :
ImportError: cannot import name 'Config' from 'homeassistant.core'

Background:
The integration fails to load on Home Assistant 2026.1.0 with an ImportError. Home Assistant 2026.1 removed the deprecated Config class from homeassistant.core. It was due to be removed in 2025.11 but It seems it wan't until 2026.1.